import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Dung Tien',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Nguyen Van A',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Sirius T-shirt',
      slug: 'sirius-t-shirt',
      category: 'Shirts',
      image: '/images/sirius-t-shirt.jpeg',
      price: 27,
      countInStock: 10,
      brand: 'ArtkeyUniverse',
      rating: 4.5,
      numReviews: 10,
      description: 'Inspired by: Sirius Artisan Keycap by the Artkey Team',
    },
    {
      // _id: '2',
      name: 'Sirius Keychain',
      slug: 'sirius-keychain',
      category: 'Keychain',
      image: '/images/sirius-keychain.jpeg',
      price: 25,
      countInStock: 15,
      brand: 'ArtkeyUniverse',
      rating: 3.5,
      numReviews: 14,
      description: 'Inspired by: Sirius Artisan Keycap by the Artkey Team',
    },
    {
      // _id: '3',
      name: 'Sirius & Goodoo',
      slug: 'sirius-goodoo-deskpad',
      category: 'Deskpad',
      image: '/images/sirius-goodoo-deskpad.jpeg',
      price: 30,
      countInStock: 5,
      brand: 'ArtkeyUniverse',
      rating: 1.5,
      numReviews: 10,
      description: 'Shipping Date: 2 weeks after date of purchase',
    },
    {
      // _id: '4',
      name: 'Gaia Dora',
      slug: 'gaia-dora',
      category: 'Artisan',
      image: '/images/gaia-dora.jpeg',
      price: 130,
      countInStock: 5,
      brand: 'ArtkeyUniverse',
      rating: 2,
      numReviews: 20,
      description: 'high quality shirt',
    },
    {
      // _id: '5',
      name: 'Pot Puff',
      slug: 'pot-puff',
      category: 'Artisan',
      image: '/images/pot-puff.jpeg',
      price: 115,
      countInStock: 0,
      brand: 'ArtkeyUniverse',
      rating: 5,
      numReviews: 10,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    {
      // _id: '6',
      name: 'A-Team',
      slug: 'a-team',
      category: 'Artisan',
      image: '/images/a-team.jpeg',
      price: 615,
      countInStock: 10,
      brand: 'ArtkeyUniverse',
      rating: 3,
      numReviews: 20,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    {
      // _id: '7',
      name: 'Neonize',
      slug: 'neonize',
      category: 'Artisan',
      image: '/images/neonize.jpeg',
      price: 85,
      countInStock: 12,
      brand: 'ArtkeyUniverse',
      rating: 1,
      numReviews: 22,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    { 
      name: 'Bushido',
      slug: 'bushido',
      category: 'Artisan',
      image: '/images/bushido.jpeg',
      price: 285,
      countInStock: 7,
      brand: 'ArtkeyUniverse',
      rating: 3,
      numReviews: 15,
      description: 'FIND THE ANSWER OF THIS QUESTION TO ENTER THE RAFFLE: WHAT IS THE LAST BATTLE OF THE SAMURAI?',
    },
    { 
      name: 'Leafy Trinity',
      slug: 'leafy-trinity',
      category: 'Artisan',
      image: '/images/leafy-trinity.jpeg',
      price: 185,
      countInStock: 22,
      brand: 'ArtkeyUniverse',
      rating: 3.5,
      numReviews: 11,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    { 
      name: 'Sirius Adventure',
      slug: 'sirius-adventure',
      category: 'Deskpad',
      image: '/images/sirius-adventure.jpeg',
      price: 30,
      countInStock: 2,
      brand: 'ArtkeyUniverse',
      rating: 4,
      numReviews: 20,
      description: 'Please note that if you buy from 2 units, we may need to contact you for the additional shipping fee.',
    },
    { 
      name: 'Voidscape',
      slug: 'voidscape',
      category: 'Artisan',
      image: '/images/voidscape.jpeg',
      price: 333,
      countInStock: 32,
      brand: 'ArtkeyUniverse',
      rating: 4.5,
      numReviews: 21,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    { 
      name: 'Deep Dive',
      slug: 'deep-dive',
      category: 'Artisan',
      image: '/images/deep-dive.jpeg',
      price: 99,
      countInStock: 7,
      brand: 'ArtkeyUniverse',
      rating: 5,
      numReviews: 9,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    { 
      name: 'Deadbot',
      slug: 'deadbot',
      category: 'Artisan',
      image: '/images/deadbot.jpeg',
      price: 140,
      countInStock: 8,
      brand: 'ArtkeyUniverse',
      rating: 4.5,
      numReviews: 10,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    { 
      name: 'Loveblind',
      slug: 'loveblind',
      category: 'Artisan',
      image: '/images/loveblind.jpeg',
      price: 385,
      countInStock: 52,
      brand: 'ArtkeyUniverse',
      rating: 4,
      numReviews: 19,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    {
      name: 'Clementina',
      slug: 'clementina',
      category: 'Artisan',
      image: '/images/clementina.jpeg',
      price: 666,
      countInStock: 31,
      brand: 'ArtkeyUniverse',
      rating: 3.5,
      numReviews: 32,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    { 
      name: 'Cherry Crystal',
      slug: 'cherry-crystal',
      category: 'Artisan',
      image: '/images/cherry-crystal.jpeg',
      price: 320,
      countInStock: 6,
      brand: 'ArtkeyUniverse',
      rating: 2,
      numReviews: 15,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    {
      // _id: '--------------------',
      name: 'OG Voidscape',
      slug: 'og-voidscape',
      category: 'Figure',
      image: '/images/og-voidscape.jpeg',
      price: 999,
      countInStock: 12,
      brand: 'ArtkeyUniverse',
      rating: 5,
      numReviews: 99,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
  ],
};

export default data;
