import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Dung Tien',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Nguyen Van A',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Sirius T-shirt',
      slug: 'sirius-t-shirt',
      category: 'Shirts',
      image: '/images/sirius-t-shirt.jpeg',
      price: 27,
      countInStock: 10,
      brand: 'ArtkeyUniverse',
      rating: 4.5,
      numReviews: 10,
      description: 'Inspired by: Sirius Artisan Keycap by the Artkey Team',
    },
    {
      // _id: '2',
      name: 'Sirius Keychain',
      slug: 'sirius-keychain',
      category: 'Keychain',
      image: '/images/sirius-keychain.jpeg',
      price: 25,
      countInStock: 15,
      brand: 'ArtkeyUniverse',
      rating: 3.5,
      numReviews: 14,
      description: 'Inspired by: Sirius Artisan Keycap by the Artkey Team',
    },
    {
      // _id: '3',
      name: 'Sirius & Goodoo Deskpad',
      slug: 'sirius-goodoo-deskpad',
      category: 'Deskpad',
      image: '/images/sirius-goodoo-deskpad.jpeg',
      price: 30,
      countInStock: 5,
      brand: 'ArtkeyUniverse',
      rating: 1.5,
      numReviews: 10,
      description: 'Shipping Date: 2 weeks after date of purchase',
    },
    {
      // _id: '4',
      name: 'Gaia Dora',
      slug: 'gaia-dora',
      category: 'Artisan',
      image: '/images/gaia-dora.jpeg',
      price: 130,
      countInStock: 5,
      brand: 'ArtkeyUniverse',
      rating: 2,
      numReviews: 20,
      description: 'high quality shirt',
    },
    {
      // _id: '5',
      name: 'Pot Puff',
      slug: 'pot-puff',
      category: 'Artisan',
      image: '/images/pot-puff.jpeg',
      price: 115,
      countInStock: 0,
      brand: 'ArtkeyUniverse',
      rating: 5,
      numReviews: 10,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    {
      // _id: '5',
      name: 'A-Team',
      slug: 'a-team',
      category: 'Artisan',
      image: '/images/a-team.jpeg',
      price: 615,
      countInStock: 10,
      brand: 'ArtkeyUniverse',
      rating: 3,
      numReviews: 20,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
    {
      // _id: '5',
      name: 'Neonize',
      slug: 'neonize',
      category: 'Artisan',
      image: '/images/neonize.jpeg',
      price: 85,
      countInStock: 12,
      brand: 'ArtkeyUniverse',
      rating: 1,
      numReviews: 22,
      description: 'CHECK THIS OUT TO NEVER MISS A RAFFLE WIN.',
    },
  ],
};

export default data;
